apiVersion: apps/v1
kind: Deployment #OBJETO QUE MANTIENE UN ESTADO DESEADO DE PODS
metadata:
  name: nginx
  namespace: default
spec:   # CONFIGURACION DESEADA DEL DEPLOYMENT
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template: # CONFIGURACION DE LOS PODS
    metadata:
      labels:
        app: nginx
    spec: # CONFIGURACION DESEADA DE LOS PODS
      containers:
        - name: nginx
          image: 087692765125.dkr.ecr.us-east-1.amazonaws.com/cloud-dashboard:v1.0.0
          ports:
            - containerPort: 80